[versions]
compose = "1.0.1"  # update kotlinCompilerExtensionVersion in compose-convention.gradle.kts
coroutines = "1.5.1"
retrofit = "2.9.0"
gson = "2.8.6"
room = "2.3.0"
koin= "3.1.2"
lifecycle = "2.4.0-alpha02"
navigation = "2.3.5"
accompanist = "0.17.0"

[libraries]
android-core = "androidx.core:core-ktx:1.6.0"
android-appcompat = "androidx.appcompat:appcompat:1.3.1"
android-material = "com.google.android.material:material:1.3.0"
android-fragment = "androidx.fragment:fragment-ktx:1.3.3"
activity-compose = "androidx.activity:activity-compose:1.4.0-alpha01"

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-icons = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
compose-iconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-navigation = "androidx.navigation:navigation-compose:2.4.0-alpha07"
compose-constraintLayout = "androidx.constraintlayout:constraintlayout-compose:1.0.0-beta02"
compose-lottie = "com.airbnb.android:lottie-compose:4.0.0"
compose-coil = "io.coil-kt:coil-compose:1.3.2"

accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pagerIndicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
gsonConverter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
loggingInterceptor = "com.squareup.okhttp3:logging-interceptor:4.9.1"

lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycle" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

datastore = "androidx.datastore:datastore-preferences:1.0.0-alpha08"

navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

firebase-bom = "com.google.firebase:firebase-bom:27.1.0"
firebase-messaging =  { module = "com.google.firebase:firebase-messaging" }

google-maps = "com.google.android.gms:play-services-maps:17.0.0"
google-mapsKtx = "com.google.maps.android:maps-ktx:2.3.0"
google-location = "com.google.android.gms:play-services-location:18.0.0"

[bundles]
coroutines = ["coroutines-core", "coroutines-android"]
compose = ["compose-ui", "compose-tooling", "compose-foundation", "compose-material"]
room = ["room-runtime", "room-ktx"]